export const REQUESTED_CHARACTERS = 'REQUESTED_CHARACTERS';
export const REQUESTED_CHARACTERS_SUCCEEDED = 'REQUESTED_CHARACTERS_SUCCEEDED';
export const REQUESTED_CHARACTERS_FAILED = 'REQUESTED_CHARACTERS_FAILED';